services:
  frontend:
    image: ghcr.io/wooshcz/sitecheckup-fe
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: sitecheckup-frontend
    ports:
      - "8080:8000"
    env_file:
      - frontend/.env
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "1.0"
        reservations:
          memory: 128M
          cpus: "0.1"
    restart: always

  worker:
    image: ghcr.io/wooshcz/sitecheckup-worker
    build:
      context: worker
      dockerfile: Dockerfile
    container_name: sitecheckup-worker
    env_file:
      - worker/.env
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.1"
    restart: always
    depends_on:
      - frontend

  nginx:
    image: docker.io/nginx:latest
    container_name: sitecheckup-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    restart: always
