FROM docker.io/nginx:1.27-bookworm

LABEL org.opencontainers.image.authors="wooshcz@gmail.com" \
    org.opencontainers.image.source=https://github.com/wooshcz/sitecheckup \
    version="1.2"

COPY nginx.conf.template /etc/nginx/templates/default.conf.template