name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for FE
      run: |
        cd frontend
        docker build . --file Dockerfile --tag sitecheckup-fe:$(date +%s)

    - name: Build the Docker image for Worker
      run: |
        cd worker
        docker build . --file Dockerfile --tag sitecheckup-worker:$(date +%s)
